### ISSUE TITLE
貌似出问题了

### ISSUE THREAD

**Issue by basheewang** [cute-jumper/bing-dict.el#15]
当调用 bing-dict-brief的时候，出现下面的error信息：

Debugger entered--Lisp error: (wrong-type-argument listp #<hash-table equal 3/65 0x2a9fb25>)
  assoc-default("Completion" #<hash-table equal 3/65 0x2a9fb25>)
  bing-dict-brief("Completion")
  funcall-interactively(bing-dict-brief "Completion")
  call-interactively(bing-dict-brief nil nil)
  command-execute(bing-dict-brief)

麻烦请更新一下，多谢！

**Comment by ice1000** [comment]
遇到了同样的问题

**Comment by ice1000** [comment]
简单调查了一下，发现了解决方法：删除`~/.emacs.d/var/bing-dict/`里面的那个文件就好了。旧版本生成了一段elisp在那调用，新版本改变了和那段elisp交互的逻辑，出现了问题。
